export const GET_ACCOUNT_DETAILS = 'ACCOUNT/GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT/GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAILURE = 'ACCOUNT/GET_ACCOUNT_DETAILS_FAILURE';
