export const LOGIN_ACCOUNT = 'ACCOUNT/LOGIN';
export const LOGIN_ACCOUNT_SUCCESS = 'ACCOUNT/LOGIN_SUCCESS';
export const LOGIN_ACCOUNT_FAILURE = 'ACCOUNT/LOGIN_FAILURE';
export const LOGOUT_ACCOUNT = 'ACCOUNT/LOGOUT';
export const GET_ACCOUNT_DETAILS = 'ACCOUNT/GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT/GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAILURE = 'ACCOUNT/GET_ACCOUNT_DETAILS_FAILURE';
